name: Medical Chatbot CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

    # Step 1: Checkout code
    - name: Checkout Repository
      uses: actions/checkout@v4


    # Step 2: Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    # Step 3: Install dependencies (CI check)
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt


    # Step 4: Login to Docker Hub (CD)
    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    # Step 5: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/medical-chatbot:latest .


    # Step 6: Push Docker Image
    - name: Push Docker Image
      if: github.event_name == 'push'
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/medical-chatbot:latest